### ISSUE TITLE
Streams interrupted and restarted during recording

### ISSUE THREAD

**Issue by revunix** [jrudess/streamdvr#166]
Hi,

I’ve noticed that streams are being interrupted and restarted periodically when recording with `streamdvr`. This issue does not occur when recording the same streams directly with `streamlink` or using `streamdvr`. The interruptions seem inconsistent—sometimes the recording lasts for 4 hours, sometimes for only 1 hour, and occasionally there are no interruptions at all. I checked the logs, but there’s nothing indicating why this is happening.

I'm using the following configuration:

```yaml
name: TWITCH
plugin: ./lib/plugins/basic
siteUrl: https://www.twitch.tv/
urlback: ""
enable: true
m3u8fetch: scripts/m3u8_streamlink.sh
m3u8fetch_args: ["--twitch-proxy-playlist=https://as.luminous.dev/,https://twitch.zzls.xyz"]
recorder: scripts/record_streamlink.sh
recorder_args: ["--twitch-proxy-playlist=https://as.luminous.dev/,https://twitch.zzls.xyz"]
scanInterval: 300
batchSize: 5
noTerminateOffline: false
streamers:
  - - montanablack88
  - - papaplatte
  - - therealknossi
  - - hsu_live
  - - thiseguysessions
    - unpaused
```
config.yaml
```yaml
enable:
  daemon: false
recording:
  autoConvertType: mp4
  captureDirectory: "/media/twitch/capturing"
  completeDirectory: "/media/twitch/captured"
  postprocess: "scripts/postprocess_ffmpeg.sh"
  dateFormat: "YYYYMMDD_HHmmss"
  fileNameFormat: "%n_%s_%d"
  includeSiteInDir: false
  streamerSubdir: true
  siteSubdir: true
  keepTsFile: false
  minSize: 0
  maxSize: 0
postprocess: ""
log:
  enable: true
  append: true
tui:
  enable: true
  allowUnicode: true
colors:
  name: magenta
  state: yellow
  offline: blue
  prompt: blue
  file: green
  time: grey
  site: green
  cmd: grey
  debug: yellow
  error: red
proxy:
  enable: false
  server:
debug:
  log: true
  recorder: true
  errortrace: true
```

Do you have any idea what might be causing this issue? Is there perhaps a difference in how `streamdvr` processes streams?

Thanks for the help!
